### ISSUE TITLE
Admin käyttöliittymä vaatii täyttämään Created by kentän, vaikka tiedot on tuotu tietokanta-ajona.

### ISSUE THREAD

**Issue by Seula** [mikko-ahonen/tanssinet#50]
![kuva](https://github.com/mikko-ahonen/tanssinet/assets/6505733/56429dc1-43f0-4edd-a27c-2a7827533526)

Admin käyttöliittymä vaatii täyttämään  tapahtumapaikkaa muokattaessa Created by kentän, vaikka tiedot on tuotu tietokanta-ajona.
Järjestelmä tuntee kuitenkin tiedon tulleen "initial import". Kyseistä vaihtoehtoa ei kuitenkaan ole mahdollisuus valita.

**Comment by mikko-ahonen** [comment]
Korjattu
